name = "Vital"
author = "SkywardMC"
version = "1.1.0+1.21.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad5c6d4d8ad943d8f8eacbcb35bd486c3c826d331dc76894622f0556f2926439"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
