name = "Vital"
author = "SkywardMC"
version = "1.0.0+1.21.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "100ce56897a774bfbdb983706e57155b69d261d59f9f6b9083b257ca789fb557"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
