name = "Vital"
author = "SkywardMC"
version = "1.1.0+1.21.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "446e3d2ccb02e14c1573e95a933e4db4b777a73303fd0f0cf603979054bc537f"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
