name = "Vital"
author = "SkywardMC"
version = "1.0.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d834bd036b65ecf8b8e08928c836cf3a8f163b255529f20db27bc0575bf82ac"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
