name = "Vital"
author = "SkywardMC"
version = "1.0.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b6558d7a8be61693ac4ba6f877a60cfef82915e6cd9b38c279867b1c1fb09f8"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
