name = "Vital"
author = "SkywardMC"
version = "1.1.1+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "785f9bb6d026e824a0abcf695695e1632969d55974c8839c9a1676569a31c626"

[versions]
fabric = "0.16.5"
minecraft = "1.20.6"
