name = "Vital"
author = "SkywardMC"
version = "1.0.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7cbac075351915a366eca29745791213d9d75a9d9798946f19231af8a56e0a1"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
