name = "Additive"
author = "SkywardMC"
version = "1.29.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ede13db6e6004e374c27f1dbd5f7cbb45517594603b25a00c6de6420fc6f2c40"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
