name = "Vital"
author = "SkywardMC"
version = "1.1.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f8498886c7bf5e059f3d81f3291c1b174a15cf83547ff9f9f1ac754727b1970"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
