name = "Additive"
author = "SkywardMC"
version = "1.29.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a000ce146bb4921d2b6249d0b5400115fa4364a9a746c8b46c4bd7e04e44ea4"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
