name = "Vital"
author = "usevital, SkywardMC"
version = "2.0.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23d87455ae8d1a6d93151aa4ceb68274e449b84d9419edec823f7a4162c723e8"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
