name = "Vital"
author = "usevital, SkywardMC"
version = "2.0.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e606cbc1b4b32ef7424177aa79b65b20898099ba0b4d5be70ed4bb8377dd868"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
