name = "Vital"
author = "SkywardMC"
version = "1.1.1+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a50adbca015541c8f3c6714eed9a86203153e6aad765dc2b30eb0f80bc2e081"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
