name = "Vital"
author = "SkywardMC"
version = "1.1.1+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c7ffd2d7153476c45382e9e8ac26c6bf12b81629c783e80415540caae9814ec"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
