name = "Vital"
author = "SkywardMC"
version = "1.1.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "add29fe6c70d1e4bfb6ec72410663fed2414f47294793fb811b36e5df1acb552"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
