name = "Vital"
author = "SkywardMC"
version = "1.0.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f83c1f768a4deb82be1b97135e161fbeeb93ede78e9fbecc03bf7a81f2e1c819"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
