name = "Vital"
author = "SkywardMC"
version = "1.0.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "619ab1dd076287fd22cffbf90ac7134d504c73d095f94444998147859ce49fae"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
