name = "Additive"
author = "SkywardMC"
version = "1.29.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "852925c2cd43f8164fe0a666c9da5a656cc293ecf6f6bb928b8deedd653e0cdf"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
