name = "Vital"
author = "SkywardMC"
version = "1.1.1+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c46767f7a8799e7dbbf2869c1c57e1baca888b7a22cc740ddbe8e144c672c9d"

[versions]
fabric = "0.16.5"
minecraft = "1.20.4"
