name = "Vital"
author = "SkywardMC"
version = "1.1.1+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a44fd297d1f6267a25d72a53fb5c4782118690727ad41c23f643787326ac5939"

[versions]
fabric = "0.16.5"
minecraft = "1.20.4"
