name = "Additive"
author = "SkywardMC"
version = "1.29.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7af3ce0d1729e512166efac1e9e97f433ba7957428099930319884b5c8dd009"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
