name = "Vital"
author = "SkywardMC"
version = "1.0.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df79617448433619a30a18d032be1c28193858c5cc69ce3bd8c711e4786b5157"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
