name = "Vital"
author = "usevital, SkywardMC"
version = "2.1.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a669be35f002aae55f3ed929cff5f54abcbfffe86b4baa9b249dfa7268c20b02"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
