name = "Vital"
author = "usevital, SkywardMC"
version = "2.1.1+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cb7bed316d06203c212b4c4f23b5e364a42ceed660091d0efabf0baad9fe45f"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
