name = "Vital"
author = "SkywardMC"
version = "1.1.1+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93ca060009f2d7bc6c29ea32075f99a73b8b6df3794205d76a56c58712de4f42"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
