name = "Vital"
author = "SkywardMC"
version = "1.0.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ced85b0abbda75744c3507f07d34538c651c1b44243cd76af5b01371e9b6d357"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
