name = "Vital"
author = "usevital, SkywardMC"
version = "2.0.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a642ce5a350b89f17fe13f277b0027b6045c3666f9d2794058e3d14b8c101b33"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
