name = "Vital"
author = "SkywardMC"
version = "1.1.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e4e1e333effbac4c13adccf791559b8b752e683248731c873a2cd845cf25815"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
