name = "Vital"
author = "SkywardMC"
version = "1.2.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "539edbeea6e91e7b5d3fa9a7b6e4f652e8e1a88afba4ef6a26cbaa5d90f1afe4"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
