name = "Vital"
author = "SkywardMC"
version = "1.0.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b11f2a0eea1bdee8d3cb0f2fb8ed1769cfbfd26702cd44ebeb72219bc902c5f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
