name = "Vital"
author = "usevital, SkywardMC"
version = "2.0.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b5c99fd4efb4383cba979ab4e9e09323a9c9fc5e46ca9c57c1a219089ee98a0"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
