name = "Vital"
author = "SkywardMC"
version = "1.1.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "620500ebcd745f6aed79eef457ff2a26e86d5a6e1dfebf321cd154f3ae10cf79"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
