name = "Additive"
author = "SkywardMC"
version = "1.31.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e8372a416f6903b7a8ad9ab50465d3856e15cda6a3ea9125028eaa8bcc95b83"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
