name = "Vital"
author = "usevital, SkywardMC"
version = "2.0.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "928dc6e3b2b2d41b94e6883deaf7aa390feb54ba5fed2294377ef20ce4f90f97"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
