name = "Vital"
author = "SkywardMC"
version = "1.1.1+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c1130304f3d05dae530bf1c2c8daa57d41c9c3a56d127d1a00933bd938c5da8"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
