name = "Vital"
author = "usevital, SkywardMC"
version = "2.0.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6511cc36e805f535c42cc6b29897c80d3bb6080e3fc738002d46bfd289ad695"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
